rm -rf "build"
rm -rf "coverage"
mkdir "build"
cmake -S "." -B "build" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_TOOLCHAIN_FILE="~/vcpkg/scripts/buildsystems/vcpkg.cmake"
cmake --build "build" --config "Release" --target "JustlyTests"
mkdir "coverage"
lcov --capture --initial --include  "*/Justly/src/*" --directory "build" --output-file "coverage/initial-lcov.info"
cd "build"
ctest -C "Release" --output-on-failure --no-tests=error
cd ".."
lcov --capture --include  "*/Justly/src/*" --directory "build" --output-file "coverage/final-lcov.info"
lcov --add-tracefile "coverage/initial-lcov.info" --add-tracefile "coverage/final-lcov.info" --output-file "coverage/lcov.info"