on:
  release:
    types: [created]
jobs:
  release_matrix:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: bramtayl/Justly/.github/workflows/install_csound_workflow.yml@master
    - uses: bramtayl/Justly/.github/workflows/install_qt_workflow.yml@master
    - run: |
      mkdir "build"
      cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_TOOLCHAIN_FILE="${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake"
      cmake --build "${{github.workspace}}/build" --config "Release" --target "Justly"
      cd "build"
      cpack --config "CPackConfig.cmake"
      cd ".."
    - uses: bramtayl/Justly/.github/workflows/upload_workflow.yml@master
