on:
  push:
    tags:
      - "v*.*.*"
jobs:
  ubuntu_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.1'
    - run: |
        Qt6_ROOT="${Qt6_DIR}"
        git clone --branch "Csound" "https://github.com/bramtayl/vcpkg.git"
        ./vcpkg/bootstrap-vcpkg.sh
        sudo apt install libxcb-cursor-dev
        mkdir "build"
        cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_TOOLCHAIN_FILE="${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake"
        cmake --build "${{github.workspace}}/build" --config "Release" --target "Justly"
        cd "build"
        cpack --config "CPackConfig.cmake"
        cd ".."
    - uses: softprops/action-gh-release@v1
      with:
        files:
          Justly-0.3.0-Linux.tar.gz
  macos_job:
    runs-on: macos-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
    - uses: actions/checkout@v3
    - uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.1'
    - run: |
        Qt6_ROOT="${Qt6_DIR}"
        git clone --branch "Csound" "https://github.com/bramtayl/vcpkg.git"
        ./vcpkg/bootstrap-vcpkg.sh
        mkdir "build"
        cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_TOOLCHAIN_FILE="${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake"
        cmake --build "${{github.workspace}}/build" --config "Release" --target "Justly"
        cd "build"
        cpack --config "CPackConfig.cmake"
        cd ".."
    - uses: softprops/action-gh-release@v1
      with:
        files:
          Justly-0.3.0-Darwin.tar.gz
  windows_job:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
    - uses: actions/checkout@v3
    - uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.1'
    - run: |
        $env:Qt6_ROOT="${env:Qt6_DIR}"
        git clone --branch "Csound" "https://github.com/bramtayl/vcpkg.git"
        ./vcpkg/bootstrap-vcpkg.bat
        mkdir "build"
        cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_TOOLCHAIN_FILE="${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake"
        cmake --build "${{github.workspace}}/build" --config "Release" --target "Justly"
    - name: Install winget
      uses: Cyberboss/install-winget@v1
    - run:
        winget install -e --id NSIS.NSIS
        cd "build"
        cpack --config "CPackConfig.cmake"
        cd ".."
    - uses: softprops/action-gh-release@v1
      with:
        files:
          Justly-0.3.0-win65.exe
