on:
  push:
    tags:
      - "v*.*.*"
jobs:
  ubuntu_job:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Release]
    steps:
    - uses: actions/checkout@v3
    - uses: jurplel/install-qt-action@v3
      with:
        version: "6.5.1"
        - uses: actions/checkout@v3
    - run: git clone --branch "Csound" "https://github.com/bramtayl/vcpkg.git"
    - if: ${{matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'}}
      name: "Unix setup"
      run: |
        Qt6_ROOT="${Qt6_DIR}"
        ./vcpkg/bootstrap-vcpkg.sh
    - if: ${{matrix.os == 'windows-latest'}}
      name: "Windows setup"
      run: |
        $env:Qt6_ROOT="${env:Qt6_DIR}"
        vcpkg/bootstrap-vcpkg.bat
    - if: ${{matrix.os == 'ubuntu-latest'}}
      run: sudo apt install libxcb-cursor-dev
    - run: mkdir "build"
    - run: cmake -S "." -B "build" -DCMAKE_BUILD_TYPE="${{matrix.build_type}}" -DCMAKE_TOOLCHAIN_FILE="vcpkg/scripts/buildsystems/vcpkg.cmake"
    - run: cmake --build "build" --config "${{matrix.build_type}}" --target "Justly"  
    - run: cpack -C "${{matrix.build_type}}" --config "build/CPackConfig.cmake"
    - uses: softprops/action-gh-release@v1
      with:
        files:
          Justly-*-*.exe
          Justly-*-*.tar.gz