on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  ubuntu_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
    - uses: actions/checkout@v3
    - uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.1'
        - uses: actions/checkout@v3
    - name: "Set Qt root"
      run: Qt6_ROOT="${Qt6_DIR}"
    - name: "Set up vcpkg"
      run: | 
        git clone --branch "Csound" "https://github.com/bramtayl/vcpkg.git"
        ./vcpkg/bootstrap-vcpkg.sh
    - name: "Build JustlyTests"
      run: |
        mkdir "build"
        cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE="${{matrix.build_type}}" -DCMAKE_TOOLCHAIN_FILE="${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake"
        cmake --build "${{github.workspace}}/build" --config "${{matrix.build_type}}" --target "JustlyTests"
    - name: "Initial coveage"
      run: | 
        sudo apt install lcov
        lcov --capture --initial --include "${{github.workspace}}/src/*" --directory "${{github.workspace}}/build" --output-file "${{github.workspace}}/coverage/initial-lcov.info"
    - name: "Run tests"
      run: |
        cd "build"
        ctest -C "${{matrix.build_type}}" --output-on-failure --no-tests=error
        cd ".."
    - name: "Final coverage"
      run: |
        lcov --capture --include "${{github.workspace}}/src/*" --directory "${{github.workspace}}/build" --output-file "${{github.workspace}}/coverage/final-lcov.info"
        lcov --add-tracefile "${{github.workspace}}/coverage/initial-lcov.info" --add-tracefile "${{github.workspace}}/coverage/final-lcov.info" --output-file "${{github.workspace}}/coverage/raw-lcov.info"
    - uses: codecov/codecov-action@v3
      with:
        files: ${{github.workspace}}/coverage/lcov.info
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
  macos_job:
    runs-on: macos-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
    - uses: actions/checkout@v3
    - uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.1'
    - name: "Set Qt root"
      run: Qt6_ROOT="${Qt6_DIR}"
    - name: "Set up vcpkg"
      run: | 
        git clone --branch "Csound" "https://github.com/bramtayl/vcpkg.git"
        ./vcpkg/bootstrap-vcpkg.sh
    - name: "Build JustlyTests"
      run: |
        mkdir "build"
        cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE="${{matrix.build_type}}" -DCMAKE_TOOLCHAIN_FILE="${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake"
        cmake --build "${{github.workspace}}/build" --config "${{matrix.build_type}}" --target "JustlyTests"
    - name: "Run tests"
      run: |
        cd "build"
        ctest -C "${{matrix.build_type}}" --output-on-failure --no-tests=error
        cd ".."
  windows_job:
    runs-on: windows-latest
    continue-on-error: true
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
    - uses: actions/checkout@v3
    - uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.1'
    - run: |
        $env:Qt6_ROOT="${env:Qt6_DIR}"
        git clone --branch "Csound" "https://github.com/bramtayl/vcpkg.git"
        ./vcpkg/bootstrap-vcpkg.bat
        mkdir "build"
        cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE="${{matrix.build_type}}" -DCMAKE_TOOLCHAIN_FILE="${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake"
        cmake --build "${{github.workspace}}/build" --config "${{matrix.build_type}}" --target "JustlyTests"
        cd "build"
        ctest -C "${{matrix.build_type}}" --output-on-failure --no-tests=error
        cd ".."
      continue-on-error: true
    - uses: mxschmitt/action-tmate@v3
       