on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  ubuntu_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
    - uses: actions/checkout@v3
    - run: |
        sudo apt install libgl1-mesa-dev qt6-base-dev
        git clone --branch "Csound" "https://github.com/bramtayl/vcpkg.git"
        ./vcpkg/bootstrap-vcpkg.sh
        ./vcpkg/vcpkg install "csound"
        mkdir "build"
        cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE="${{matrix.build_type}}" -DCMAKE_TOOLCHAIN_FILE="${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake"
        cmake --build "${{github.workspace}}/build" --config "${{matrix.build_type}}" --target "Justly"
        cd "build"
        ctest -C "${{matrix.build_type}}" --output-on-failure
        cd ".."
  macos_job:
    runs-on: macos-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
    - uses: actions/checkout@v3
    - run: |
        brew install qt
        git clone --branch "Csound" "https://github.com/bramtayl/vcpkg.git"
        ./vcpkg/bootstrap-vcpkg.sh
        ./vcpkg/vcpkg install "csound"
        mkdir "build"
        cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE="${{matrix.build_type}}" -DCMAKE_TOOLCHAIN_FILE="${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake"
        cmake --build "${{github.workspace}}/build" --config "${{matrix.build_type}}" --target "Justly"
        cd "build"
        ctest -C "${{matrix.build_type}}" --output-on-failure
        cd ".."
  windows_job:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
    - uses: actions/checkout@v3
    - uses: jurplel/install-qt-action@v3
      with:
        version: '6.4.1'
    - run: |
        $env:Qt6_ROOT="${env:Qt6_DIR}"
        git clone --branch "Csound" "https://github.com/bramtayl/vcpkg.git"
        ./vcpkg/bootstrap-vcpkg.bat
        ./vcpkg/vcpkg install "csound:x64-windows"
        mkdir "build"
        cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE="${{matrix.build_type}}" -DCMAKE_TOOLCHAIN_FILE="${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake"
        cmake --build "${{github.workspace}}/build" --config "${{matrix.build_type}}" --target "Justly"
        cd "build"
        ctest -C "${{matrix.build_type}}" --output-on-failure
        cd ".."