on:
  workflow_call:

jobs:
  ubuntu_job:
    runs-on: ubuntu-latest
    steps:
    - run: |
        RELEASE_ID=$(jq --raw-output ".release.id" "$GITHUB_EVENT_PATH")
        curl -X "POST" -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" --upload-file "${{github.workspace}}/build/Justly-0.1.0-Darwin.tar.gz" --header "Content-Type:application/octet-stream" "https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${RELEASE_ID}/assets?name=Justly-0.1.0-Darwin.tar.gz"
  mac_job:
    runs-on: macos-latest
    steps: 
    - run: |
        RELEASE_ID=$(jq --raw-output ".release.id" "$GITHUB_EVENT_PATH")
        curl -X "POST" -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" --upload-file "${{github.workspace}}/build/Justly-0.1.0-Darwin.tar.gz" --header "Content-Type:application/octet-stream" "https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${RELEASE_ID}/assets?name=Justly-0.1.0-Darwin.tar.gz"
  windows_job:
    runs-on: windows-latest
    steps:
    - name: release_step
    - run: |
      iwr -useb get.scoop.sh -outfile 'install.ps1'
      .\install.ps1 -RunAsAdmin
      scoop update
      scoop bucket add extras
      scoop install nsis curl jq
      $env:RELEASE_ID = jq --raw-output ".release.id" "${env:GITHUB_EVENT_PATH}"
      curl.exe -X "POST" -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" --upload-file "${{github.workspace}}/build/Justly-0.1.0-win64.exe" --header "Content-Type:application/octet-stream" "https://uploads.github.com/repos/${env:GITHUB_REPOSITORY}/releases/${env:RELEASE_ID}/assets?name=Justly-0.1.0-win64.exe"
