on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  main_job:
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v3.5.3
      with:
        submodules: true

     # install Qt
    - uses: jurplel/install-qt-action@v3.3.0
      with:
        version: "6.5.1"
        cache: true
    - if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: Qt6_ROOT="${Qt6_DIR}"
    - if: matrix.os == 'windows-latest'
      run: $env:Qt6_ROOT="${env:Qt6_DIR}"

    # install nsis
    - if: matrix.os == 'windows-latest'
      uses: Cyberboss/install-winget@v1
    - if: matrix.os == 'windows-latest'
      run: winget install -e --id NSIS.NSIS --accept-source-agreements

    # install xcb-cursor
    - if: matrix.os == 'ubuntu-latest'
      run: sudo apt install libxcb-cursor-dev

    - uses: lukka/get-cmake@v3.27.1
    - uses: lukka/run-vcpkg@v11.1
      with:
        vcpkgJsonGlob: 'vcpkg.json'
    - uses: lukka/run-cmake@v10.6
      with:
        configurePreset: 'configure-preset'
        buildPreset: 'build-preset'
        testPreset: 'test-release-preset'
        packagePreset: 'package-preset'
    - if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v0.1.15
      with:
        files:
          # e.g. Justly-0.1.0-win64.exe
          build/Justly-*-*.exe
          build/Justly-*-*.tar.gz
