on:
  push:
env:
  instruments_url: "https://ftp.osuosl.org/pub/musescore/soundfont/MuseScore_General"
jobs:
  main_job:
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-latest, macos-13, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
    - name: Download
      uses: actions/checkout@v4.1.7
    
    - name: Install dependencies on Ubuntu
      if: matrix.os == 'ubuntu-24.04'
      run: > 
        sudo apt install
        cmake
        fluidsynth
        libfluidsynth-dev
        pipx
        qt6-base-dev
        qt6-wayland

    - name: Install gcovr on Ubuntu
      if: matrix.os == 'ubuntu-24.04'
      run: pipx install gcovr

    - name: Install dependencies on MacOS
      if: matrix.os == 'macos-latest' || matrix.os == 'macos-13'
      run: brew install cmake fluid-synth ninja qt 

    - name: Add MSVC to path on Windows
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1.12.1

    - name: Install cmake on Windows
      if: matrix.os == 'windows-latest'
      uses: lukka/get-cmake@v3.29.6

    - name: Install winget to get Windows packages
      if: matrix.os == 'windows-latest'
      uses: Cyberboss/install-winget@v1

    - name: Install winzip on Windows
      if: matrix.os == 'windows-latest'
      run: winget install -e --id Corel.WinZip --accept-source-agreements

    - name: Install cURL on Windows
      if: matrix.os == 'windows-latest'
      run: winget install -e --id cURL.cURL
  
    - name: Install Qt on Windows
      if: matrix.os == 'windows-latest'
      uses: jurplel/install-qt-action@v4.0.0
      with:
        version: "6.6.3"
        cache: true

    - name: Install vcpkg packages
      uses: lukka/run-vcpkg@v11.5
      with:
        vcpkgGitCommitId: '47364fbc300756f64f7876b549d9422d5f3ec0d3'

    - name: Restore soundfont files from the cache if available
      id: soundfont_step
      uses: actions/cache@v4.0.2
      with:
        path: share
        key: ${{matrix.os}}-soundfont_cache

    - name: Download the soundfont if not in the cache
      if: steps.soundfont_step.outputs.cache-hit != 'true'
      run: >
        curl "${{env.instruments_url}}/MuseScore_General.sf2"
        --output "share/MuseScore_General.sf2"

    - name: Download the soundfont license if not in the cache
      if: steps.soundfont_step.outputs.cache-hit != 'true'
      run: >
        curl "${{env.instruments_url}}/MuseScore_General_License.md"
        --output "share/MuseScore_General_License.md"
    
    - name: Configure debug on unix
      if: matrix.os != 'windows-latest'
      run: >
        cmake -S . -B build
        -DCMAKE_BUILD_TYPE=Debug
        -DNO_SPEAKERS=ON
        -DTRACK_COVERAGE=ON
        -DBUILD_TESTS=ON
        -DCMAKE_VERBOSE_MAKEFILE=ON
        -DCMAKE_TOOLCHAIN_FILE=${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake
        -DVCPKG_OVERLAY_PORTS=$(pwd)/overlays/fluidsynth

    - name: Configure debug on Windows
      if: matrix.os == 'windows-latest'
      run: >
        cmake -S . -B build
        -DCMAKE_BUILD_TYPE=Debug
        -DNO_SPEAKERS=ON
        -DTRACK_COVERAGE=OFF
        -DBUILD_TESTS=ON
        -DCMAKE_VERBOSE_MAKEFILE=ON
        -DCMAKE_TOOLCHAIN_FILE=${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake

    - name: Build debug
      run: cmake --build build --config Debug

    - name: Test offscreen on Unix
      if: matrix.os != 'windows-latest'
      run: cd build; QT_QPA_PLATFORM=offscreen ctest --build-config Debug --verbose

    - name: Test on Windows
      if: matrix.os == 'windows-latest'
      run: cd build; ctest --build-config Debug --verbose
    
    - name: Run gcovr on Ubuntu
      if: matrix.os == 'ubuntu-24.04'
      run: gcovr --exclude "build/.*" --xml "coverage.xml"

    - name: Upload code coverage
      uses: codecov/codecov-action@v4.5.0
      if: matrix.os == 'ubuntu-24.04'
      with:
        fail_ci_if_error: true
        files: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Remove old build folder on Unix
      if: matrix.os != 'windows-latest'
      run: rm -rf build

    - name: Remove old build folder on Windows
      if: matrix.os == 'windows-latest'
      run: Remove-Item -Path "build" -Recurse -Force

    - name: Configure release on Unix
      if: matrix.os != 'windows-latest'
      run: >
        cmake -S . -B build
        -DCMAKE_BUILD_TYPE=Release
        -DNO_SPEAKERS=OFF
        -DTRACK_COVERAGE=OFF
        -DBUILD_TESTS=OFF
        -DCMAKE_VERBOSE_MAKEFILE=ON
        -DCMAKE_TOOLCHAIN_FILE=${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake
        -DVCPKG_OVERLAY_PORTS=$(pwd)/overlays/fluidsynth
        
    - name: Configure release on Windows
      if: matrix.os == 'windows-latest'
      run: >
        cmake -S . -B build
        -DCMAKE_BUILD_TYPE=Release
        -DNO_SPEAKERS=OFF
        -DTRACK_COVERAGE=OFF
        -DBUILD_TESTS=OFF
        -DCMAKE_VERBOSE_MAKEFILE=ON
        -DCMAKE_TOOLCHAIN_FILE=${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake

    - name: Build release
      run: cmake --build build --config Release

    - name: Package on MacOS 13
      if: matrix.os == 'macos-13'
      run: cd build; cpack -G ZIP -C Release -P Justly-x64

    - name: Package on MacOS latest
      if: matrix.os == 'macos-latest'
      run: cd build; cpack -G ZIP -C Release -P Justly-arm64

    - name: Package on Windows
      if: matrix.os == 'windows-latest'
      run: cd build; cpack -G ZIP -C Release
    
    - name: Package on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: cd build; cpack -G TGZ -C Release

    - name: Release on a new tag
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2.0.6
      with:
        files: |
          **/Justly-*-*.tar.gz
          **/Justly-*-*.zip

